### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by Natxo09** [MabelMedia-LLC/Fabric-Mods#1]
Add autocomplete for homes, and a /homes command to list all the homes

**Comment by MabelYT** [comment]
Hello, Thanks For Sharing This Idea!

If This Is A Good Fit For SuperSimpleHome, You'll Be Able To Use It Once v1.2.0 Is Released :)

I'll Let You Know When I Have Updates Regarding This @Natxo09

**Comment by MabelYT** [comment]
Hello, I've Just Released v1.2.0!
It Now Has The "/homes" Command You Requested, And v1.2.1 Will Add The Autocomplete For Home Names.

**Comment by Natxo09** [comment]
That was quick as lightning, thank you very much! @MabelYT

**Comment by MabelYT** [comment]
Thanks For Your Support! @Natxo09
