### ISSUE TITLE
Error: An unexpected error ocurred trying to execute that command.

### ISSUE THREAD

**Issue by Natxo09** [MabelMedia-LLC/Fabric-Mods#2]
Let me explain: The mod is installed both on the server and on the clients. When you set a home, everything works perfectly, even the two recommendations I mentioned yesterday. The problem arises when you restart the server; when you try to teleport to the saved homes, it gives the error I mentioned to you. It's as if it "loses" or doesn't remember the homes. When I hover over the chat error, it says the following; I'm not sure if it can help you:

![image](https://github.com/MabelMedia-LLC/Fabric-Mods/assets/122750516/cebcffbf-b567-400e-8a97-5802b07a506d)

**Comment by MabelYT** [comment]
Hello!

Did You Close The Server Gracefully, Or Did You Crash It?

**Comment by Natxo09** [comment]
I am shutting down the server using the command 'stop'.

**Comment by Natxo09** [comment]
1.20.6 Client and Server

**Comment by MabelYT** [comment]
What Version Of SuperSimpleHome?

**Comment by Natxo09** [comment]
Last one 1.2.1

**Comment by Natxo09** [comment]
In the MabelMedia.SuperSimpleHome.json file, it seems that the homes are being recorded correctly, on both (Client and Server)

**Comment by MabelYT** [comment]
I've Managed To Narrow Down The Offending Code To A Few Lines, But I Can't Reproduce The Issue Locally.

It May Be Due To A Conflict Caused By Another Mod.

Could You Send A List Of Mods Your Server Has?

**Comment by MabelYT** [comment]
Also, Mod's Not Needed On The Client When You're Using It On The Server, That's Just For SinglePlayer.

**Comment by MabelYT** [comment]
Thanks! I'm Looking Into It, And Hopefully It Should Be Fixed For v1.2.2.

**Comment by MabelYT** [comment]
I'll Let You Know When It's Sorted

**Comment by Natxo09** [comment]
Great, thank you. If you notice any incompatibility, let me know, it might be my mistake... Thanks again.

**Comment by MabelYT** [comment]
Could You Also Try Moving The Config File, And Try Starting The Server Without it?

**Comment by MabelYT** [comment]
I Think It Might Be A Change In The Format

**Comment by Natxo09** [comment]
I've tried removing the MabelMedia.SuperSimpleHome.json file and having it regenerate, as well as removing the client mod and also deleting the MabelMedia.SuperSimpleHome.json from the client, but nothing works. I register a new home, restart the server, and the same error occurs

**Comment by MabelYT** [comment]
You Don't Need The Mod On The Client, When Playing On A Server

**Comment by Natxo09** [comment]
Yes, that's why I've already deleted it, since during the server test I also removed it from the client, as you told me it wasn't necessary

**Comment by MabelYT** [comment]
:)

I'm Also In The Process Of Building A Debugging Version of 1.2.2, That I'd Like You To Run To Get A StackTrace Of The Error.

**Comment by Natxo09** [comment]
Okay, whatever you need

**Comment by MabelYT** [comment]
I've Managed To Reproduce The Issue Locally :)

Now We Cookin

**Comment by MabelYT** [comment]
![Screenshot_20240504_160559](https://github.com/MabelMedia-LLC/Fabric-Mods/assets/51007720/0e58922c-bc78-47fa-bcfe-7e70ce22ee37)

**Comment by Natxo09** [comment]
Nicee!

**Comment by MabelYT** [comment]
I Found The Exact Broken Code, Investigating...

**Comment by MabelYT** [comment]
Alright, Are You Free To Test If My Fix Works?

**Comment by Natxo09** [comment]
Yep

**Comment by MabelYT** [comment]
[SuperSimpleHome-1.zip](https://github.com/MabelMedia-LLC/Fabric-Mods/files/15210177/SuperSimpleHome-1.zip)
Here, If This Works, It'll Be The Final Release Build.

**Comment by Natxo09** [comment]
Do you recommend deleting the JSON and having it regenerate?

**Comment by MabelYT** [comment]
Please Let Me Know If The Problem Is Solved (Btw, You'll Need To Delete The Config, The Format's Been Rewritten)

**Comment by MabelYT** [comment]
Also, If This Works, It'll Make The Config Much Smaller :)

**Comment by Natxo09** [comment]
Perfect, everything seems to be working fine. On another note, while looking at the JSON, I noticed that several users are using the same name for certain homes. I assume there's no issue with that, right?

**Comment by MabelYT** [comment]
Nope, I've Written It So All Player's Data Are Seperated.
The Power Of Future Proofing 🚀

**Comment by MabelYT** [comment]
Alright, I'm Gonna Mark This As Fixed, And Drop v1.2.2.

Thanks Again For Your Help & Support @Natxo09 ❤️

**Comment by Natxo09** [comment]
As I told you the other day, thank you very much, lightning fast as always!! Good job.

**Comment by MabelYT** [comment]
Always Happy To Lend A Hand :)
