### ISSUE TITLE
1.20.4 backport crashes

### ISSUE THREAD

**Issue by Cpt-Dingus** [MabelMedia-LLC/Fabric-Mods#4]
Am making a new issue as you instructed. Launching the backport makes minecraft crash with the following log:

Full log: https://mclo.gs/C4epgnV

**Comment by MabelYT** [comment]
The Issue Has Been Resolved.

**Comment by MabelYT** [comment]
Funny Part Is, I Found This Out At The Same Time You Did.

**Comment by MabelYT** [comment]
Nevermind, Gonna Drop Hotfix 2 In A Minute.

**Comment by MabelYT** [comment]
Fixed It Now.

**Comment by Cpt-Dingus** [comment]
Looks good, thanks!

**Comment by MabelYT** [comment]
You're Welcome 🎉
