### ISSUE TITLE
/home command not working

### ISSUE THREAD

**Issue by Daggerdiego107** [MabelMedia-LLC/Fabric-Mods#5]
I was trying to use the /home command and it is not working it displays an error in the chat that says "An unexpected error occured trying to use this command" I even updated the mod to ensure it was not the update and it still showed the error

**Comment by MabelYT** [comment]
Is This v1.2.5?

**Comment by MabelYT** [comment]
Have You Tried Resetting Your Config File?

**Comment by Daggerdiego107** [comment]
Yes

**Comment by MabelYT** [comment]
What's THe Name Of The Home You've Set?

**Comment by MabelYT** [comment]
I'm Not Sure What Happened Here, But If You Want Me To Help Fix This, Make A New Issue.
