### ISSUE TITLE
[BUG] Can Hit Invisible Armor Stand Holograms

### ISSUE THREAD

**Issue by ExiledLizard** [MabelMedia-LLC/Fabric-Mods#7]
Hey, @MabelYT, I recently tried out this mod, and the hologram's armor stand is still hittable, preventing interaction trough it. You could implement the armor stand spawned by the command, to have the **Marker** **NBT** variable set to true.

**Comment by MabelYT** [comment]
Thanks For Bringing This Up, I'll Take A Look Into It :)

**Comment by MabelYT** [comment]
v1.1.2 Solves The Issue, And Also Solves The Bug Of The Armour Stands Sticking Down Pressure Plates, Which Broke MabelSMP's Minigames Teleporters. Cheers!

**Comment by ExiledLizard** [comment]
Thanks!
